config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new'

  root to: 'static_pages#index'
  get '/help', to: 'static_pages#help'

  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :items , only: [:new , :show]
  resources :ownerships , only: [:create , :destroy]
  resources :relationships, only:[:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/have.rb
class Have < Ownership
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :ownerships , foreign_key: "item_id", dependent: :destroy
  has_many :users, through: :ownerships

  has_many :wants, class_name: "Want", foreign_key: "item_id", dependent: :destroy
  has_many :want_users , through: :wants, source: :user

  has_many :haves, class_name: "Have", foreign_key: "item_id", dependent: :destroy
  has_many :have_users , through: :haves, source: :user
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :user, class_name: "User"  # ユーザー
  belongs_to :item, class_name: "Item"  # 商品
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :following_relationships, class_name: "Relationship",foreign_key: "follower_id", dependent: :destroy
  has_many :following_users, through: :following_relationships, source: :followed

  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower

  has_many :ownerships , foreign_key: "user_id", dependent: :destroy
  has_many :items, through: :ownerships

  has_many :wants, class_name: "Want", foreign_key: "user_id", dependent: :destroy
  has_many :want_items , through: :wants, source: :item

  has_many :haves, class_name: "Have", foreign_key: "user_id", dependent: :destroy
  has_many :have_items , through: :haves, source: :item

  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password


  # follow,unfollowメソッド
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  def following?(other_user)
    following_users.include?(other_user)
  end

  # have,wantメソッド
  def have(item)
    haves.find_or_create_by(item_id: item.id)
  end

  def unhave(item)
    haves.find_by(item_id: item.id).destroy
  end

  def have?(item)
    have_items.find_by(item_code: item['itemCode'])
  end

  def want(item)
    wants.find_or_create_by(item_id: item.id)
  end

  def unwant(item)
    wants.find_by(item_id: item.id).destroy
  end

  def want?(item)
    want_items.find_by(item_code: item['itemCode'])
  end
end

app/models/want.rb
class Want < Ownership
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user , except: [:show]
  before_action :set_item, only: [:show]

  def new
    if params[:q]
      response = RakutenWebService::Ichiba::Item.search(
        keyword: params[:q],
        imageFlag: 1,
      )
      @items = response.first(20)
    end
  end

  def show
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  before_action :logged_in_user

  def create
    if params[:item_code]
      @item = Item.find_or_initialize_by(item_code: params[:item_code])
    else
      @item = Item.find(params[:item_id])
    end

    if @item.new_record?
      items = RakutenWebService::Ichiba::Item.search(
        itemCode: params[:item_code],
        imageFlag: 1,
      )

      item                  = items.first
      @item.title           = item['itemName']
      @item.small_image     = item['smallImageUrls'].first['imageUrl']
      @item.medium_image    = item['mediumImageUrls'].first['imageUrl']
      @item.large_image     = item['mediumImageUrls'].first['imageUrl'].gsub('?_ex=128x128','')
      @item.detail_page_url = item['itemUrl']
      @item.save!
    end

    if params[:type] == "Have"
      current_user.have(@item)
    else
      current_user.want(@item)
    end

  end

  def destroy
    @item = Item.find(params[:item_id])

    if params[:type] == "Have"
      current_user.unhave(@item)
    else
      current_user.unwant(@item)
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @items = Item.all.order("updated_at DESC").limit(30)
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return fully each page title
  def full_title(page_title = '')
    base_title = "Monolist"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ownerships_helper.rb
module OwnershipsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/items/_have.html.slim
= link_to "" , ownerships_path(item_id: item.id , type: "Have") ,
                      :class => "have-#{item.id} btn-have btn btn-warning btn-sm have",
                      :remote => true,
                      :method => :post

app/views/items/_items.html.slim
.container
  .container-inner.inner-default.clearfix
    -items.each do |item|
      .item-box
        .image
          .img-wrap
            = image_tag(item['mediumImageUrls'].first['imageUrl'].gsub('?_ex=128x128', '') , alt: item['itemName'])
        .detail
          p.title
            a href="#{item['itemUrl']}"  #{item['itemName']}
        .action.clearfix
          -if current_user.want?(item)
            ==render 'unwant',item: current_user.want?(item)
          -else
            = link_to "", ownerships_path(item_code: item['itemCode'] , type: "Want") ,
                        :class => "btn-want btn btn-danger btn-sm want",
                        :item_code => "want-#{item['itemCode']}",
                        :remote => true,
                        :method => :post
          -if current_user.have?(item)
            == render 'unhave',item: current_user.have?(item)
          -else
            = link_to "", ownerships_path(item_code: item['itemCode'] , type: "Have") ,
                        :class => "btn-have btn btn-warning btn-sm have",
                        :item_code => "have-#{item['itemCode']}",
                        :remote => true,
                        :method => :post

app/views/items/_list.html.slim
.container
  .container-inner.inner-default.clearfix
    - items.each do |item|
      .item-box
        .image
          .img-wrap
            -if item.large_image.present?
              = image_tag(item.large_image, alt: item.title)
            -else
              = image_tag("no-image.png", alt: item.title)
        .detail
          p.title
            =link_to "#{item.title}","#{item.detail_page_url}"
        .action.clearfix
          -if current_user
            -if current_user.want_items.include?(item)
              ==render 'items/unwant',item: item
            -else
              = link_to "", ownerships_path(item_id: item.id , type: "Want") ,
                          :class => "btn-want btn btn-danger btn-sm want",
                          :item_code => "want-#{item.item_code}",
                          :remote => true,
                          :method => :post
            -if current_user.have_items.include?(item)
              == render 'items/unhave',item: item
            -else
              = link_to "", ownerships_path(item_id: item.id , type: "Have") ,
                          :class => "btn-have btn btn-warning btn-sm have",
                          :item_code => "have-#{item.item_code}",
                          :remote => true,
                          :method => :post
            = link_to "詳細", item, class: "btn btn-info btn-sm"

app/views/items/_unhave.html.slim
= link_to "" ,
  ownership_path(current_user.haves.find_by(:item_id => item.id) ,
    item_id: item.id , type: "Have") ,
  :class => "have-#{item.id} btn-have btn btn-warning btn-sm have_it",
  :remote => true,
  :method => :delete

app/views/items/_unwant.html.slim
= link_to "" , 
    ownership_path(current_user.wants.find_by(:item_id => item.id) , 
      item_id: item.id , type: "Want") ,
    :class => "want-#{item.id} btn-want btn btn-danger btn-sm want_it",
    :remote => true,
    :method => :delete

app/views/items/_want.html.slim
= link_to "" , ownerships_path(item_id: item.id , type: "Want") ,
    :class => "want-#{item.id} btn-want btn btn-danger btn-sm want",
    :remote => true,
    :method => :post

app/views/items/new.html.slim
.jumbotron style="color:#FFF;  background:url(#{asset_path 'search.jpg'});  background-size:cover;"
  h2 アイテムを検索
.search
  = form_tag new_item_path , method: :get do
    = text_field_tag :q , params[:q], placeholder: "キーワードを入力", required: true
    = submit_tag "アイテムを検索", name: nil , class: "btn btn-success", data: { disable_with: "検索中..."}
.search-result
  -if @items.present?
    .alert.alert-info
      span.glyphicon.glyphicon-info-sign aria-hidden="true"
      |
        気になったアイテムが欲しければ「Want」持ってれば「Have」しましょう
    == render 'items' , items: @items
  -elsif params[:q].present?
    .alert.alert-danger
      span.glyphicon.glyphicon-remove-sign aria-hidden="true"
      検索したアイテムはありません

app/views/items/show.html.slim
.container
  .container-inner.inner-sm.clearfix
    .item-single-main
      .image
        .img-wrap
          = image_tag(@item.large_image , alt: @item.title)
      .title
        |#{@item.title}
    .item-single-side
      .side-box
        .side-box-title Haveしたユーザー #{@item.have_users.count}人
        .side-box-body
           -@item.have_users.each do |have_user|
             =link_to  gravatar_for(have_user,size:30),have_user
             span style="margin-right: 1em;"

      .side-box
        .side-box-title Wantしたユーザー #{@item.want_users.count}人
        .side-box-body
          -@item.want_users.each do |want_user|
            =link_to gravatar_for(want_user,size:30),want_user
            span style="margin-right: 1em;"
      .text-center
        = link_to('楽天詳細ページへ', @item.detail_page_url)

app/views/ownerships/create.js.slim
-if params[:type] == "Have"
  | $(".have-#{@item.id},[item_code='have-#{@item.item_code}']").replaceWith("#{escape_javascript(render('items/unhave' , item: @item))}");
-else
  | $(".want-#{@item.id},[item_code='want-#{@item.item_code}']").replaceWith("#{escape_javascript(render('items/unwant' , item: @item))}");

| $('.btn-have,.btn-want').removeAttr('disabled');

app/views/ownerships/destroy.js.slim
-if params[:type] == "Have"
 | $(".have-#{@item.id},[item_code='have-#{@item.item_code}']").replaceWith("#{escape_javascript(render('items/have' , item: @item))}");
-else
 | $(".want-#{@item.id},[item_code='want-#{@item.item_code}']").replaceWith("#{escape_javascript(render('items/want' , item: @item))}");

|$('.btn-have,.btn-want').removeAttr('disabled');

app/views/relationships/create.js.slim
|$("#follow_form").html("#{escape_javascript(render('users/unfollow'))}");

app/views/relationships/destroy.js.slim
|$("#follow_form").html("#{escape_javascript(render('users/follow'))}");

app/views/static_pages/help.html.slim
.jumbotron style="color:#FFF;  background:url(#{asset_path 'search.jpg'});  background-size:cover;"
  h2 色々ヘルプしてくれるページ

.row
  .col-md-6.col-md-offset-3
    p WantとかHaveとか適当に押して自分の欲しいもの管理
    p 他の人のリストも見れる

app/views/static_pages/index.html.slim
.jumbotron style="color:#FFF;  background:url(#{asset_path 'monolist.jpg'});  background-size:cover;"
  h1  Monolist
  = link_to '会員登録', signup_path, class: "btn btn-success btn-lg"

==render 'items/list',items: @items

app/views/users/_follow.html.slim
= form_for(current_user.following_relationships.build, remote: true) do |f|
  =hidden_field_tag :followed_id, @user.id
  button.btn.btn-success.btn-round type="submit"
    span.glyphicon.glyphicon-plus aria-hidden="true"
    |Follow

app/views/users/_follow_form.html.slim
-if current_user != @user
  #follow_form
    -if current_user.following?(@user)
      == render 'unfollow'
    -else
      == render 'follow'

app/views/users/_unfollow.html.slim
= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f|
  button.btn.btn-info.btn-round
    span.glyphicon.glyphicon-ok aria-hidden="true"
    |Following

app/views/users/_user_status.html.slim
.status
  ul
    li
      .status-label FOLLOWING
      .status-value #{@user.following_users.count}
    li
      .status-label FOLLOWER
      .status-value #{@user.follower_users.count}
    li
      .status-label WANT
      .status-value #{@user.want_items.count}
    li
      .status-label HAVE
      .status-value #{@user.have_items.count}
  -if logged_in?
    ==render 'follow_form'

app/views/users/new.html.slim
.jumbotron style="color:#FFF;  background:url(#{asset_path 'search.jpg'});  background-size:cover;"
  h2 会員登録

.box
  h2.box-title Signup
  .box-inner
    = form_for(@user) do |f|
      = render 'shared/error_messages', object: f.object

      .form-group
        = f.text_field :name, class: "form-control", placeholder: "お名前"
      .form-group
        = f.text_field :email, class: "form-control", placeholder: "メールアドレス"
      .form-group
        = f.password_field :password, class: "form-control", placeholder: "パスワード"
      .form-group
        = f.password_field :password_confirmation, class: "form-control", placeholder: "パスワード（確認）"
      .submit-group
        = f.submit "登録する", class: "btn btn-success"

app/views/users/show.html.slim
.user_profile
  .icon
    =gravatar_for @user
  .name
    =@user.name

  .status
    ul
      li
        .status-label FOLLOWING
        .status-value #{@user.following_users.count}
      li
        .status-label FOLLOWER
        .status-value #{@user.follower_users.count}
      li
        .status-label WANT
        .status-value #{@user.want_items.count}
      li
        .status-label HAVE
        .status-value #{@user.have_items.count}
    -if logged_in?
      ==render 'follow_form'
-if current_user == @user
  h2 あなたがHaveもしくはWantしているアイテム一覧
-else
  h2 #{@user.name}さんがHaveもしくはWantしているアイテム一覧
== render 'items/list',items: @items